# Site
title: Hexo
author: o2team

url: http://aotu.io/halojs/
root: /halojs/
permalink: api/:title.html

new_post_name: :title.md # File name of new posts
default_layout: post
external_link: true # Open external links in new tab
highlight:
  enable: false
skip_render:
  - demo/**
  - src/**

theme: hexo-theme-doc

deploy:
  type: git
  repo: https://github.com/o2team/halojs.git
