# Site
title: Hexo
author: o2team

url: http://aotu.io/halojs/
root: /halojs/
permalink: api/:title.html

new_post_name: :title.md
default_layout: post
external_link: true
highlight: false
public_dir: public
skip_render:
  - demo/**
  - src/**


theme: hexo-theme-doc

deploy:
  - type: git
    repo: https://github.com/o2team/halojs.git

# custom settings
internal_port: 3000
internal_dir: internal

external_port: 3001
external_dir: external
