# Site
title: Hexo
author: o2team

url: http://littly.github.io/external
root: /external/
permalink: api/:title.html

new_post_name: :title.md
default_layout: post
external_link: true
highlight: false
public_dir: external
deploy_dir: deploy_external
skip_render:
    - demo/**
    - src/**

theme: hexo-theme-doc

#deploy:
#    - type: git
#      repo: git@github.com:Littly/littletest.git

environment: external
repo: git@github.com:Littly/external.git