# Site
title: Hexo
author: o2team

url: http://aotu.io/halojs
root: /halojs/
permalink: api/:title.html

new_post_name: :title.md
default_layout: post
external_link: true
highlight: false
public_dir: external
deploy_dir: .deploy_external
skip_render:
    - demo/**
    - src/**

theme: hexo-theme-doc


environment: external
repo: git@github.com:o2team/halojs.git