# Site
title: Hexo
author: o2team

url: http://aotu.io/halojs
root: /halojs/
permalink: api/:title.html

new_post_name: :title.md
default_layout: post
external_link: true
highlight: false
public_dir: internal
deploy_dir: .deploy_internal
skip_render:
    - demo/**
    - src/**

theme: hexo-theme-doc


environment: internal
repo: git@github.com:Littly/internal.git