# Site
title: Hexo
author: o2team

url: http://littly.github.io/internal
root: /internal/
permalink: api/:title.html

new_post_name: :title.md
default_layout: post
external_link: true
highlight: false
public_dir: internal
deploy_dir: deploy_internal
skip_render:
    - demo/**
    - src/**

theme: hexo-theme-doc

#deploy:
#    - type: git
#      repo: git@github.com:Littly/littletest.git

environment: internal
repo: git@github.com:Littly/internal.git