# Site
title: Hexo
author: o2team

url: http://aotu.io/halojs/internal
root: /halojs/internal/
permalink: api/:title.html

new_post_name: :title.md
default_layout: post
external_link: true
highlight: false
public_dir: internal
skip_render:
    - demo/**
    - src/**


theme: hexo-theme-doc

deploy:
    - type: git
      repo: https://github.com/o2team/halojs.git

environment: internal
